services:
  - type: web
    name: myalumniapp
    env: dotnet
    buildCommand: "dotnet publish -c Release -o out"
    startCommand: "dotnet out/MyAlumniApp.dll"
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
